id: 3cx-config
info:
  name: 3CX Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    3CX Configuration file was discovered.
  reference:
    - https://www.3cx.com/docs/configure-pbx-automatically/
  classification:
    cwe-id:
      - CWE-219
      - CWE-552
  metadata:
    max-request: 1
    shodan-query: html:"setupconfig.xml"
    verified: true
  tags: 3cx,config,exposure,vuln
http:
  - matchers:
      - condition: and
        part: body
        type: word
        words:
          - 3CX
          - <SetupConfig
      - part: content_type
        type: word
        words:
          - application/xml
    matchers-condition: and
    method: GET
    path:
      - '{{BaseURL}}/SetupConfig.xml'
