id: accueil-wampserver
info:
  name: Accueil WAMPSERVER Configuration Page - Detect
  author: tess
  severity: medium
  description: Accueil WAMPSERVER configuration page was detected.
  remediation: Restrict access to the WAMP server configuration page and sub-tools.
  reference:
    - https://www.wampserver.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
    cpe: cpe:2.3:a:wampserver:wampserver:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: wampserver
    shodan-query: http.title:"Accueil WAMPSERVER"
    vendor: wampserver
    verified: true
  tags: accueil,config,exposure,vuln,wampserver
http:
  - matchers:
      - condition: and
        part: body
        type: word
        words:
          - Accueil WAMPSERVER
          - Configuration Serveur
      - status:
          - 200
        type: status
    matchers-condition: and
    method: GET
    path:
      - '{{BaseURL}}'
