id: smtp-credentials-exposure
info:
  name: SMTP Credentials Exposure - Detection
  author: pussycat0x
  severity: high
  description: |
    Detects exposed SMTP credentials (username and password) in a webpage's HTML or JavaScript source code.
  metadata:
    max-request: 1
    shodan-query: html:"smtp_password"
    verified: true
  tags: config,credentials,exposure,smtp
http:
  - extractors:
      - group: 1
        internal: true
        name: username
        part: body
        regex:
          - smtp_username":"(.*?)"
          - <smtp_username>(.*)</smtp_username>
        type: regex
      - group: 1
        internal: true
        name: password
        part: body
        regex:
          - smtp_password":"(.*?)"
          - <smtp_password>(.*)</smtp_password>
        type: regex
      - dsl:
          - '"Username: "+ username'
          - '"PASSWORD: "+ password'
        # digest: 4b0a00483046022100ece48c1e6701b782f611447639c710f761fc424e5af0cb685a2ef91f7be51a16022100e23af2cf625f41e0ff80e15a66a6fd52922c265f83a2c47de1f1597fd3decc47:922c64590222798bb761d5b6d8e72950

        type: dsl
    host-redirects: true
    matchers:
      - condition: and
        dsl:
          - contains_all(body, "smtp_username","smtp_password")
          - status_code == 200
        type: dsl
    max-redirects: 2
    method: GET
    path:
      - '{{BaseURL}}'
