id: webpack-config
info:
  name: Webpack Configuration File - Detect
  author: ambassify,s4e-io
  severity: info
  description: Webpack configuration file was detected.
  reference:
    - https://webpack.js.org/configuration/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:webpack.js:webpack:*:*:*:*:node.js:*:*:*
  metadata:
    max-request: 1
    product: webpack
    shodan-query: html:"webpack.config.js"
    vendor: webpack.js
  tags: config,exposure,vuln
http:
  - matchers:
      - condition: or
        type: word
        words:
          - module.exports
          - const
      - condition: or
        part: header
        type: word
        words:
          - application/javascript
          - text/javascript
      - case-insensitive: true
        negative: true
        part: body
        type: word
        words:
          - <html
          - <!doctype
      - status:
          - 200
        type: status
    matchers-condition: and
    method: GET
    path:
      - '{{BaseURL}}/webpack.config.js'
