id: amp-application-panel
info:
  name: Application Management Panel - Detect
  author: DhiyaneshDK
  severity: info
  description: Application Management Panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cubecoders:amp:*:*:*:*:*:*:*:*
  metadata:
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)amp - application management panel"})
    fofa-query: title="amp - application management panel"
    google-query: intitle:"amp - application management panel"
    max-request: 1
    product: amp
    shodan-query:
      - title:"AMP - Application Management Panel"
      - http.title:"amp - application management panel"
    vendor: cubecoders
    verified: true
  tags: amp,cubecoders,discovery,panel
http:
  - matchers:
      - type: word
        words:
          - <title>AMP - Application Management Panel</title>
      - part: header
        type: word
        words:
          - text/html
    matchers-condition: and
    method: GET
    path:
      - '{{BaseURL}}'
