id: esphome-panel
info:
  name: ESPHome Login Panel - Detect
  author: fabaff
  severity: info
  description: ESPHome login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:esphome:esphome:*:*:*:*:*:*:*:*
  metadata:
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)login - esphome"})
    fofa-query: title="login - esphome"
    google-query: intitle:"login - esphome"
    max-request: 1
    product: esphome
    shodan-query:
      - title:"Login - ESPHome"
      - http.title:"login - esphome"
    vendor: esphome
    verified: true
  tags: discovery,esphome,iot,panel
http:
  - matchers:
      - part: body
        type: word
        words:
          - class="esphome-header
      - status:
          - 200
        type: status
    matchers-condition: and
    method: GET
    path:
      - '{{BaseURL}}/login'
